version: '2'
services:
    message-server:
        container_name: risk-profile-server
        build:
            context: docker-risk-profile-server
            dockerfile: Dockerfile
        image: message-server:latest
        ports:
            - 18888:8888
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge